project_name: tiny-dns

version: 2

builds:
  - id: main
    env:
      - CGO_ENABLED=0
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s
      - -w
      - -buildid=
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v3
      - v2
    main: ./main
    binary: tiny-dns

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Amd64 }}"
    format: tar.gz